pottery:
	@if [ ! -f dones/pottery.done ]; then \
		echo "pottery"; \
		touch dones/pottery.done; \
	fi
irrigation: pottery
	@if [ ! -f dones/irrigation.done ]; then \
		echo "irrigation"; \
		touch dones/irrigation.done; \
	fi
writing: pottery
	@if [ ! -f dones/writing.done ]; then \
		echo "writing"; \
		touch dones/writing.done; \
	fi
animal_husbandry:
	@if [ ! -f dones/animal_husbandry.done ]; then \
		echo "animal_husbandry"; \
		touch dones/animal_husbandry.done; \
	fi
archery: animal_husbandry
	@if [ ! -f dones/archery.done ]; then \
		echo "archery"; \
		touch dones/archery.done; \
	fi
mining:
	@if [ ! -f dones/mining.done ]; then \
		echo "mining"; \
		touch dones/mining.done; \
	fi
masonry: mining
	@if [ ! -f dones/masonry.done ]; then \
		echo "masonry"; \
		touch dones/masonry.done; \
	fi
bronze_working: mining
	@if [ ! -f dones/bronze_working.done ]; then \
		echo "bronze_working"; \
		touch dones/bronze_working.done; \
	fi
the_wheel: mining
	@if [ ! -f dones/the_wheel.done ]; then \
		echo "the_wheel"; \
		touch dones/the_wheel.done; \
	fi
apprenticeship: mining currency horseback_riding
	@if [ ! -f dones/apprenticeship.done ]; then \
		echo "apprenticeship"; \
		touch dones/apprenticeship.done; \
	fi
sailing:
	@if [ ! -f dones/sailing.done ]; then \
		echo "sailing"; \
		touch dones/sailing.done; \
	fi
celestial_navigation: sailing astrology
	@if [ ! -f dones/celestial_navigation.done ]; then \
		echo "celestial_navigation"; \
		touch dones/celestial_navigation.done; \
	fi
shipbuilding: sailing
	@if [ ! -f dones/shipbuilding.done ]; then \
		echo "shipbuilding"; \
		touch dones/shipbuilding.done; \
	fi
astrology:
	@if [ ! -f dones/astrology.done ]; then \
		echo "astrology"; \
		touch dones/astrology.done; \
	fi
drama_poetry: astrology irrigation masonry early_empire mysticism
	@if [ ! -f dones/drama_poetry.done ]; then \
		echo "drama_poetry"; \
		touch dones/drama_poetry.done; \
	fi
theology: astrology mysticism drama_poetry
	@if [ ! -f dones/theology.done ]; then \
		echo "theology"; \
		touch dones/theology.done; \
	fi
horseback_riding: archery
	@if [ ! -f dones/horseback_riding.done ]; then \
		echo "horseback_riding"; \
		touch dones/horseback_riding.done; \
	fi
machinery: archery iron_working engineering
	@if [ ! -f dones/machinery.done ]; then \
		echo "machinery"; \
		touch dones/machinery.done; \
	fi
currency: writing foreign_trade
	@if [ ! -f dones/currency.done ]; then \
		echo "currency"; \
		touch dones/currency.done; \
	fi
state_workforce: writing bronze_working craftsmanship
	@if [ ! -f dones/state_workforce.done ]; then \
		echo "state_workforce"; \
		touch dones/state_workforce.done; \
	fi
recorded_history: writing political_philosophy drama_poetry
	@if [ ! -f dones/recorded_history.done ]; then \
		echo "recorded_history"; \
		touch dones/recorded_history.done; \
	fi
construction: masonry the_wheel horseback_riding
	@if [ ! -f dones/construction.done ]; then \
		echo "construction"; \
		touch dones/construction.done; \
	fi
engineering: masonry the_wheel
	@if [ ! -f dones/engineering.done ]; then \
		echo "engineering"; \
		touch dones/engineering.done; \
	fi
iron_working: bronze_working
	@if [ ! -f dones/iron_working.done ]; then \
		echo "iron_working"; \
		touch dones/iron_working.done; \
	fi
mathematics: bronze_working celestial_navigation currency drama_poetry
	@if [ ! -f dones/mathematics.done ]; then \
		echo "mathematics"; \
		touch dones/mathematics.done; \
	fi
military_training: bronze_working military_tradition games_recreation
	@if [ ! -f dones/military_training.done ]; then \
		echo "military_training"; \
		touch dones/military_training.done; \
	fi
cartography: celestial_navigation shipbuilding
	@if [ ! -f dones/cartography.done ]; then \
		echo "cartography"; \
		touch dones/cartography.done; \
	fi
medieval_faires: currency feudalism
	@if [ ! -f dones/medieval_faires.done ]; then \
		echo "medieval_faires"; \
		touch dones/medieval_faires.done; \
	fi
guilds: currency feudalism civil_service
	@if [ ! -f dones/guilds.done ]; then \
		echo "guilds"; \
		touch dones/guilds.done; \
	fi
mercantilism: currency humanism
	@if [ ! -f dones/mercantilism.done ]; then \
		echo "mercantilism"; \
		touch dones/mercantilism.done; \
	fi
stirrups: horseback_riding feudalism
	@if [ ! -f dones/stirrups.done ]; then \
		echo "stirrups"; \
		touch dones/stirrups.done; \
	fi
mass_production: shipbuilding machinery education
	@if [ ! -f dones/mass_production.done ]; then \
		echo "mass_production"; \
		touch dones/mass_production.done; \
	fi
naval_tradition: shipbuilding defensive_tactics
	@if [ ! -f dones/naval_tradition.done ]; then \
		echo "naval_tradition"; \
		touch dones/naval_tradition.done; \
	fi
military_tactics: mathematics
	@if [ ! -f dones/military_tactics.done ]; then \
		echo "military_tactics"; \
		touch dones/military_tactics.done; \
	fi
education: mathematics apprenticeship
	@if [ ! -f dones/education.done ]; then \
		echo "education"; \
		touch dones/education.done; \
	fi
military_engineering: construction engineering
	@if [ ! -f dones/military_engineering.done ]; then \
		echo "military_engineering"; \
		touch dones/military_engineering.done; \
	fi
castles: construction divine_right exploration
	@if [ ! -f dones/castles.done ]; then \
		echo "castles"; \
		touch dones/castles.done; \
	fi
games_recreation: construction state_workforce
	@if [ ! -f dones/games_recreation.done ]; then \
		echo "games_recreation"; \
		touch dones/games_recreation.done; \
	fi
gunpowder: apprenticeship stirrups military_engineering
	@if [ ! -f dones/gunpowder.done ]; then \
		echo "gunpowder"; \
		touch dones/gunpowder.done; \
	fi
printing: machinery education
	@if [ ! -f dones/printing.done ]; then \
		echo "printing"; \
		touch dones/printing.done; \
	fi
metal_casting: machinery gunpowder
	@if [ ! -f dones/metal_casting.done ]; then \
		echo "metal_casting"; \
		touch dones/metal_casting.done; \
	fi
banking: education stirrups guilds
	@if [ ! -f dones/banking.done ]; then \
		echo "banking"; \
		touch dones/banking.done; \
	fi
astronomy: education
	@if [ ! -f dones/astronomy.done ]; then \
		echo "astronomy"; \
		touch dones/astronomy.done; \
	fi
military_science: stirrups printing siege_tactics
	@if [ ! -f dones/military_science.done ]; then \
		echo "military_science"; \
		touch dones/military_science.done; \
	fi
siege_tactics: castles metal_casting
	@if [ ! -f dones/siege_tactics.done ]; then \
		echo "siege_tactics"; \
		touch dones/siege_tactics.done; \
	fi
square_rigging: cartography gunpowder
	@if [ ! -f dones/square_rigging.done ]; then \
		echo "square_rigging"; \
		touch dones/square_rigging.done; \
	fi
exploration: cartography mercenaries medieval_faires
	@if [ ! -f dones/exploration.done ]; then \
		echo "exploration"; \
		touch dones/exploration.done; \
	fi
industrialization: mass_production square_rigging
	@if [ ! -f dones/industrialization.done ]; then \
		echo "industrialization"; \
		touch dones/industrialization.done; \
	fi
scientific_theory: banking astronomy the_enlightenment
	@if [ ! -f dones/scientific_theory.done ]; then \
		echo "scientific_theory"; \
		touch dones/scientific_theory.done; \
	fi
colonialism: astronomy mercantilism
	@if [ ! -f dones/colonialism.done ]; then \
		echo "colonialism"; \
		touch dones/colonialism.done; \
	fi
ballistics: metal_casting siege_tactics
	@if [ ! -f dones/ballistics.done ]; then \
		echo "ballistics"; \
		touch dones/ballistics.done; \
	fi
economics: metal_casting scientific_theory
	@if [ ! -f dones/economics.done ]; then \
		echo "economics"; \
		touch dones/economics.done; \
	fi
scorched_earth: metal_casting nationalism
	@if [ ! -f dones/scorched_earth.done ]; then \
		echo "scorched_earth"; \
		touch dones/scorched_earth.done; \
	fi
steam_power: industrialization
	@if [ ! -f dones/steam_power.done ]; then \
		echo "steam_power"; \
		touch dones/steam_power.done; \
	fi
flight: industrialization scientific_theory economics
	@if [ ! -f dones/flight.done ]; then \
		echo "flight"; \
		touch dones/flight.done; \
	fi
steel: industrialization rifling
	@if [ ! -f dones/steel.done ]; then \
		echo "steel"; \
		touch dones/steel.done; \
	fi
class_struggle: industrialization ideology
	@if [ ! -f dones/class_struggle.done ]; then \
		echo "class_struggle"; \
		touch dones/class_struggle.done; \
	fi
sanitation: scientific_theory urbanization
	@if [ ! -f dones/sanitation.done ]; then \
		echo "sanitation"; \
		touch dones/sanitation.done; \
	fi
rifling: ballistics military_science
	@if [ ! -f dones/rifling.done ]; then \
		echo "rifling"; \
		touch dones/rifling.done; \
	fi
totalitarianism: military_science ideology
	@if [ ! -f dones/totalitarianism.done ]; then \
		echo "totalitarianism"; \
		touch dones/totalitarianism.done; \
	fi
electricity: steam_power mercantilism
	@if [ ! -f dones/electricity.done ]; then \
		echo "electricity"; \
		touch dones/electricity.done; \
	fi
radio: steam_power flight conservation
	@if [ ! -f dones/radio.done ]; then \
		echo "radio"; \
		touch dones/radio.done; \
	fi
chemistry: sanitation
	@if [ ! -f dones/chemistry.done ]; then \
		echo "chemistry"; \
		touch dones/chemistry.done; \
	fi
suffrage: sanitation ideology
	@if [ ! -f dones/suffrage.done ]; then \
		echo "suffrage"; \
		touch dones/suffrage.done; \
	fi
replaceable_parts: economics
	@if [ ! -f dones/replaceable_parts.done ]; then \
		echo "replaceable_parts"; \
		touch dones/replaceable_parts.done; \
	fi
capitalism: economics mass_media
	@if [ ! -f dones/capitalism.done ]; then \
		echo "capitalism"; \
		touch dones/capitalism.done; \
	fi
combined_arms: flight combustion
	@if [ ! -f dones/combined_arms.done ]; then \
		echo "combined_arms"; \
		touch dones/combined_arms.done; \
	fi
synthetic_materials: flight plastics
	@if [ ! -f dones/synthetic_materials.done ]; then \
		echo "synthetic_materials"; \
		touch dones/synthetic_materials.done; \
	fi
rapid_deployment: flight cold_war
	@if [ ! -f dones/rapid_deployment.done ]; then \
		echo "rapid_deployment"; \
		touch dones/rapid_deployment.done; \
	fi
advanced_ballistics: replaceable_parts steel electricity
	@if [ ! -f dones/advanced_ballistics.done ]; then \
		echo "advanced_ballistics"; \
		touch dones/advanced_ballistics.done; \
	fi
combustion: steel natural_history
	@if [ ! -f dones/combustion.done ]; then \
		echo "combustion"; \
		touch dones/combustion.done; \
	fi
computers: electricity radio suffrage totalitarianism class_struggle
	@if [ ! -f dones/computers.done ]; then \
		echo "computers"; \
		touch dones/computers.done; \
	fi
advanced_flight: radio
	@if [ ! -f dones/advanced_flight.done ]; then \
		echo "advanced_flight"; \
		touch dones/advanced_flight.done; \
	fi
rocketry: radio chemistry
	@if [ ! -f dones/rocketry.done ]; then \
		echo "rocketry"; \
		touch dones/rocketry.done; \
	fi
nanotechnology: radio composites
	@if [ ! -f dones/nanotechnology.done ]; then \
		echo "nanotechnology"; \
		touch dones/nanotechnology.done; \
	fi
mass_media: radio urbanization
	@if [ ! -f dones/mass_media.done ]; then \
		echo "mass_media"; \
		touch dones/mass_media.done; \
	fi
nuclear_program: chemistry ideology
	@if [ ! -f dones/nuclear_program.done ]; then \
		echo "nuclear_program"; \
		touch dones/nuclear_program.done; \
	fi
plastics: combustion
	@if [ ! -f dones/plastics.done ]; then \
		echo "plastics"; \
		touch dones/plastics.done; \
	fi
satellites: advanced_flight rocketry
	@if [ ! -f dones/satellites.done ]; then \
		echo "satellites"; \
		touch dones/satellites.done; \
	fi
globalization: advanced_flight rapid_deployment space_race
	@if [ ! -f dones/globalization.done ]; then \
		echo "globalization"; \
		touch dones/globalization.done; \
	fi
guidance_systems: rocketry advanced_ballistics
	@if [ ! -f dones/guidance_systems.done ]; then \
		echo "guidance_systems"; \
		touch dones/guidance_systems.done; \
	fi
space_race: rocketry cold_war
	@if [ ! -f dones/space_race.done ]; then \
		echo "space_race"; \
		touch dones/space_race.done; \
	fi
nuclear_fission: advanced_ballistics combined_arms
	@if [ ! -f dones/nuclear_fission.done ]; then \
		echo "nuclear_fission"; \
		touch dones/nuclear_fission.done; \
	fi
telecommunications: computers
	@if [ ! -f dones/telecommunications.done ]; then \
		echo "telecommunications"; \
		touch dones/telecommunications.done; \
	fi
robotics: computers globalization
	@if [ ! -f dones/robotics.done ]; then \
		echo "robotics"; \
		touch dones/robotics.done; \
	fi
lasers: nuclear_fission
	@if [ ! -f dones/lasers.done ]; then \
		echo "lasers"; \
		touch dones/lasers.done; \
	fi
cold_war: nuclear_fission ideology
	@if [ ! -f dones/cold_war.done ]; then \
		echo "cold_war"; \
		touch dones/cold_war.done; \
	fi
composites: synthetic_materials
	@if [ ! -f dones/composites.done ]; then \
		echo "composites"; \
		touch dones/composites.done; \
	fi
stealth_technology: synthetic_materials
	@if [ ! -f dones/stealth_technology.done ]; then \
		echo "stealth_technology"; \
		touch dones/stealth_technology.done; \
	fi
social_media: telecommunications professional_sports space_race
	@if [ ! -f dones/social_media.done ]; then \
		echo "social_media"; \
		touch dones/social_media.done; \
	fi
nuclear_fusion: lasers
	@if [ ! -f dones/nuclear_fusion.done ]; then \
		echo "nuclear_fusion"; \
		touch dones/nuclear_fusion.done; \
	fi
code_of_laws:
	@if [ ! -f dones/code_of_laws.done ]; then \
		echo "code_of_laws"; \
		touch dones/code_of_laws.done; \
	fi
craftsmanship: code_of_laws
	@if [ ! -f dones/craftsmanship.done ]; then \
		echo "craftsmanship"; \
		touch dones/craftsmanship.done; \
	fi
foreign_trade: code_of_laws
	@if [ ! -f dones/foreign_trade.done ]; then \
		echo "foreign_trade"; \
		touch dones/foreign_trade.done; \
	fi
military_tradition: craftsmanship
	@if [ ! -f dones/military_tradition.done ]; then \
		echo "military_tradition"; \
		touch dones/military_tradition.done; \
	fi
early_empire: foreign_trade
	@if [ ! -f dones/early_empire.done ]; then \
		echo "early_empire"; \
		touch dones/early_empire.done; \
	fi
mysticism: foreign_trade
	@if [ ! -f dones/mysticism.done ]; then \
		echo "mysticism"; \
		touch dones/mysticism.done; \
	fi
political_philosophy: state_workforce early_empire
	@if [ ! -f dones/political_philosophy.done ]; then \
		echo "political_philosophy"; \
		touch dones/political_philosophy.done; \
	fi
defensive_tactics: games_recreation political_philosophy
	@if [ ! -f dones/defensive_tactics.done ]; then \
		echo "defensive_tactics"; \
		touch dones/defensive_tactics.done; \
	fi
humanism: drama_poetry medieval_faires
	@if [ ! -f dones/humanism.done ]; then \
		echo "humanism"; \
		touch dones/humanism.done; \
	fi
mercenaries: military_training feudalism
	@if [ ! -f dones/mercenaries.done ]; then \
		echo "mercenaries"; \
		touch dones/mercenaries.done; \
	fi
feudalism: defensive_tactics
	@if [ ! -f dones/feudalism.done ]; then \
		echo "feudalism"; \
		touch dones/feudalism.done; \
	fi
civil_service: defensive_tactics recorded_history
	@if [ ! -f dones/civil_service.done ]; then \
		echo "civil_service"; \
		touch dones/civil_service.done; \
	fi
divine_right: theology civil_service
	@if [ ! -f dones/divine_right.done ]; then \
		echo "divine_right"; \
		touch dones/divine_right.done; \
	fi
diplomatic_service: guilds
	@if [ ! -f dones/diplomatic_service.done ]; then \
		echo "diplomatic_service"; \
		touch dones/diplomatic_service.done; \
	fi
reformed_church: guilds divine_right
	@if [ ! -f dones/reformed_church.done ]; then \
		echo "reformed_church"; \
		touch dones/reformed_church.done; \
	fi
the_enlightenment: humanism diplomatic_service
	@if [ ! -f dones/the_enlightenment.done ]; then \
		echo "the_enlightenment"; \
		touch dones/the_enlightenment.done; \
	fi
civil_engineering: mercantilism
	@if [ ! -f dones/civil_engineering.done ]; then \
		echo "civil_engineering"; \
		touch dones/civil_engineering.done; \
	fi
nationalism: the_enlightenment
	@if [ ! -f dones/nationalism.done ]; then \
		echo "nationalism"; \
		touch dones/nationalism.done; \
	fi
opera_ballet: the_enlightenment
	@if [ ! -f dones/opera_ballet.done ]; then \
		echo "opera_ballet"; \
		touch dones/opera_ballet.done; \
	fi
natural_history: colonialism
	@if [ ! -f dones/natural_history.done ]; then \
		echo "natural_history"; \
		touch dones/natural_history.done; \
	fi
urbanization: civil_engineering nationalism
	@if [ ! -f dones/urbanization.done ]; then \
		echo "urbanization"; \
		touch dones/urbanization.done; \
	fi
conservation: natural_history urbanization
	@if [ ! -f dones/conservation.done ]; then \
		echo "conservation"; \
		touch dones/conservation.done; \
	fi
mobilization: urbanization
	@if [ ! -f dones/mobilization.done ]; then \
		echo "mobilization"; \
		touch dones/mobilization.done; \
	fi
cultural_heritage: conservation
	@if [ ! -f dones/cultural_heritage.done ]; then \
		echo "cultural_heritage"; \
		touch dones/cultural_heritage.done; \
	fi
ideology: mass_media mobilization
	@if [ ! -f dones/ideology.done ]; then \
		echo "ideology"; \
		touch dones/ideology.done; \
	fi
professional_sports: ideology
	@if [ ! -f dones/professional_sports.done ]; then \
		echo "professional_sports"; \
		touch dones/professional_sports.done; \
	fi
